[package]
name = "kotlot"
version = "0.1.0"
authors = ["Boris Boutillier <boris.boutillier@gmail.com>"]
edition = "2018"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy" }
#bevy = { path = "/home/boris/work/rust/forks/bevy"}
#bevy = "0.2.1"
rand = "0.7.3"
ncollide2d = "0.24.0"
libm = "0.2.1"
